name: NoPiglinBrute
version: '1.0.0'

main: com.vqlt.nopiglinbrute.NoPiglinBrute
api-version: '1.21.8'
load: POSTWORLD

commands:
  disablebrutes:
    description: Enables or disables Piglin Brute spawning
    usage: /disablebrutes <true/false>